repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_checkov
  - repo: local
    hooks:
      - id: conftest
        name: conftest
        entry: conftest
        args:
          - test
          - stacks
        language: system
        pass_filenames: false
      - id: infracost
        name: infracost breakdown
        entry: infracost
        args:
          - breakdown
          - --path=stacks
          - --format=json
        language: system
        pass_filenames: false
